# Generated by Django 2.2.6 on 2019-12-21 10:06

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeluser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('is_archieve', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('color', colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#00FF00', '#0000FF'], null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('is_pin', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('collaborator', models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(blank=True, related_name='label', to='notes.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
